#!/usr/bin/env bash
# reproduce_all.sh — regenerate every CPU result/figure behind the paper from scratch.
#
# Verified environment: Python 3.11, torch 2.2.2 (CPU is fine), numpy (1.26+ or 2.x both work; a
# harmless NumPy-1.x/2.x import warning may print). No GPU needed for any of the MAIN experiments
# below; the LANGUAGE results (Qwen + LoRA) run on a single T4 via notebooks/ (see bottom).
#
#   bash reproduce_all.sh            # MAIN experiments at the paper's seed counts
#   SEEDS=3 bash reproduce_all.sh    # quicker pass (fewer seeds)
#   bash reproduce_all.sh exploratory  # also run the single-run demo pillars
#
# Each command writes results/<name>.json (+ .svg). Artifacts are committed, so a clean run should
# reproduce the committed numbers within seed noise.
set -euo pipefail
cd "$(dirname "$0")"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-4}"
SEEDS="${SEEDS:-8}"          # stats/extrapolation paper runs use 8; characterization uses 5
SEEDS5="${SEEDS5:-5}"

run () { echo; echo "=== $* ==="; python -u -m "$@"; }

echo "############ MAIN experiments (multi-seed, paper figures) ############"
run src.eval.stats             --seeds "$SEEDS"     # §6 cognitive suite: planning/value/relational/continual
run src.eval.extrapolation     --seeds "$SEEDS"     # Fig 1: length extrapolation vs fair place/GRU/oracle
run src.eval.ablations         --seeds "$SEEDS5"    # Fig 2a: range/scale/training-dist/sequence-model ablations
run src.eval.seq_baselines     --seeds "$SEEDS5"    # Fig 2b: fair Transformer baselines (the honest tie)
run src.eval.code_necessity    --seeds "$SEEDS5"    # Fig 3: capacity + remapping (where the code wins)
run src.eval.multimap_task     --seeds "$SEEDS5"    # boundary: remapping doesn't help a trained model w/ context-id
run src.eval.frontier_probes   --seeds "$SEEDS5"    # Fig 4: sample efficiency + noise (honest non-wins)
run src.eval.controls          --seeds "$SEEDS5"    # mechanism vs parameters control
run src.eval.significance      --n_fast 20 --n_slow 8   # paired tests (p-values) on every headline claim; resumable
run src.eval.torus             --seeds "$SEEDS"     # non-Euclidean (torus): periodicity NECESSARY, breaks the tie + leakage rebuttal
run src.eval.structural_transfer --seeds "$SEEDS"   # TEM: frozen space-trained metric -> relational inference (+ falsifiers)
python -u -m src.eval.phase_diagram   # SYNTHESIS: when each inductive bias wins (reads the JSONs above; no training)
run src.eval.successor         --seeds "$SEEDS"     # §7 predictive map (SR): plans detours where geometry stalls; geodesic fields; TD-learned
run src.eval.time_cells        --seeds "$SEEDS"     # §7 temporal map: time cells + scalar (Weber) timing EMERGE from a trained recurrent substrate (vs untrained control)
run src.eval.spiking_time_cells --seeds 6           # §7 SPIKING + multi-timescale: spiking time cells + emergent tau-spectrum that aids timing (vs homogeneous-tau control)
run src.eval.eprop_local_learning --seeds 5         # §7 LOCAL LEARNING: time cells emerge under e-prop (eligibility traces, NO backprop) -- the brain's learning rule
run src.eval.btsp              --seeds 5            # §7 BTSP one-shot learning (Bittner 2017): one plateau imprints a place field in ONE pass via a seconds-wide asymmetric kernel; field shifts UPSTREAM (predictive), shift scales with speed; needs seconds-scale + asymmetry (vs STDP/symmetric controls). GAPS.md #1
run src.eval.space_time_circuit --seeds 5           # §7 CIRCUIT EMBEDDING: place + time + conjunctive space-time cells coexist in ONE circuit (Neuron 2024)
run src.eval.social_space      --seeds 5            # SOCIAL SPACE (Danjo 2018, Omer 2018): one substrate fed self + OTHER-agent motion develops pure self-place + pure other-place cells (emergent, eta^2); self/other lesion double dissociation. GAPS.md #4
run src.eval.goal_vector       --seeds 5            # GOAL-VECTOR CODE (Sarel 2017; Banino 2018): a policy trained ONLY to reach randomized goals develops a goal-DIRECTION code (emergent, goal-specific vs untrained + shuffle nulls); honest scope (allocentric/redundant; ego+distance don't emerge). GAPS.md #3A
run src.eval.reward_map        --seeds 5            # REWARD MAP (Hollup 2001; Gauthier-Tank 2018): reward-triggered BTSP builds place fields that ANTICIPATE the goal (upstream shift, vanishes with symmetric kernel) + reward-specific over-representation (vs yoked-random control). GAPS.md #3B
run src.eval.hexadirectional   --seeds 5            # HEXADIRECTIONAL / GRID CODE FOR CONCEPTS (Doeller 2010; Constantinescu 2016): hex grid -> 6-fold direction signal via a movement nonlinearity (conjunctive grid x direction); symmetry INHERITED from the lattice (square -> 4-fold), linear read-out flat -> not circular. GAPS.md #2
run src.eval.neuromodulation   --seeds 5            # NEUROMODULATION (Hasselmo 2006; Yu-Dayan 2005): ACh sets encode/retrieve on a CA3 auto-associator -> high-ACh encoding blocks OVERLAP-SPECIFIC intrusion of an old memory at MATCHED write energy (recurrent contamination, not non-storage), completion needs W_rec; NE surprise = NOVELTY not change (AUC~1) and a surprise remap is adaptive two-sided (learns new env + protects old) vs a matched no-reset control. GAPS.md #5
run src.eval.hippocampal_subfields --seeds 5        # DG PATTERN SEPARATION + CA1 COMPARATOR (Marr 1971; Treves-Rolls 1994; Lisman-Grace 2005): a sparse DG expansion lets CA3 recall M=24 SIMILAR environments (0.87) where a MATCHED-SIZE dense expansion interferes (0.37, worse than not expanding -> sparsity is load-bearing, not dimensionality); separation index 0.54 vs 1.00; CA1 mismatch detects novelty (AUC 1.00) and collapses to chance (0.50) when the CA3 memory stream is ablated -> a genuine entorhinal-vs-memory comparator. Measured, never in a loss. GAPS.md #5b
run src.eval.ephaptic_coupling --seeds 5            # EPHAPTIC COUPLING (Anastassiou-Koch 2011; Chiang-Durand 2019): a self-generated ZERO-MEAN field synchronizes LIF spike TIMING (chi 1.00 vs 0.07) at MATCHED firing rate (|d rate| 0.03 -> timing not drive) where matched-budget SPARSE synapses cannot (0.11); dose-response transition; zeroing the field -> baseline; the synchrony drives a downstream coincidence detector (0.22 vs 0.01) at matched rate. A non-synaptic channel doing computational work. GAPS.md #5c
run src.eval.grid_shearing --seeds 5                # GRID SHEARING (Krupic 2015; Stensola 2015): the hexagonal grid stays hexagonal in a SQUARE (gridness 1.00) but SHEARS in a TRAPEZOID under the same boundary anchoring (0.01) -- EMERGENT, the deformation is never drawn, it falls out of the square-calibrated boundary fix mislocalizing in a non-square arena; dose-response with shear; DOUBLE-DISSOCIATION falsifier (trapezoid+no-anchor 1.14 and square+anchor 1.00 both stay hexagonal -> deformation needs BOTH geometry and anchoring). GAPS.md #5d
run src.eval.manifold_geometry --seeds 5          # MANIFOLD DEFORMATION (deeper #5d; Gardner 2022): #5d showed the RATE MAP shears -- does the NEURAL MANIFOLD itself deform, or stay a rigid torus? (A) trapezoid grid codes lie on the SAME manifold as the square's (overlap 0.88 vs reference 0.90; deformation +0.02~0) -> RIGID torus, so #5d is a space->manifold MAP warping, not a manifold deformation. (B) in a BARRIER (non-Euclidean) env the fixed grid ignores the wall (geodesic-advantage +0.02) while a PLASTIC code reshapes to the geodesic geometry (+0.27) -> manifold deformation REQUIRES plasticity, which the rigid CAN lacks. GAPS.md #5d (deeper)
run src.eval.reference_transform --seeds 5          # RSC/PPC EGO->ALLO TRANSFORM (Andersen-Zipser 1988; Byrne-Becker-Burgess 2007): a plain MLP trained ONLY on allocentric output learns the head-direction-gated rotation -- generalizes to head directions HELD OUT of training (RMSE 0.07, 4% of scale) so it is the transform not a lookup; GAIN-FIELD units emerge (27%, multiplicative ego*HD, extra-R2 0.08 vs 0.015 untrained -- Zipser-Andersen, never in the loss); shuffled-HD (0.90) and no-HD (2.24>scale) falsifiers explode. GAPS.md #5e
run src.eval.astrocyte_syncytium --seeds 5          # ASTROCYTE SYNCYTIUM (Scemes-Giaume 2006; Henneberger 2010): gap-junction Ca2+ spread binds a silent-but-surrounded synapse heterosynaptically (gate 0.95 vs 0.00 point-wise) and gates plasticity by SPATIAL DENSITY (clustered core 0.40 vs matched-count scattered 0.07); UNCOUPLED does nothing at sub-threshold drive, and a fully REGENERATIVE wave FLOODS (1.00 vs 1.00, no selectivity) -> the computation is the GRADED spread, not the wave. Honest: effect real but modest. GAPS.md #5f
run src.eval.replay_planning   --seeds 8            # REPLAY THAT COMPUTES (Foster-Wilson 2006; Pfeiffer-Foster 2013; Mattar-Daw 2018): a direction-free SCALAR priority (|TD error|, prioritized sweeping) makes value sweep BACKWARD from the reward -- reverse replay = credit assignment (reverse-frac 1.00 vs 0.50 random, p=0.009), direction NEVER encoded; the SAME map read forward = a planning rollout that routes around a barrier (100% vs 1% untrained); one value rule, opposite directions (Diba-Buzsaki dissociation); prioritized reaches a plannable map 16x fewer backups than random. GAPS.md #6
run src.eval.uncertainty_behavior --seeds 5         # UNCERTAINTY DRIVES BEHAVIOR (Ma 2006; Ernst-Banks 2002; Sreenivasan-Fiete 2011): a CALIBRATED uncertainty read from the grid population (reconstruction residual = inter-module inconsistency) is calibrated to true decode error under INDEPENDENT module drift (corr 0.87), rises 2.5x with path integration, resets at a cue -- but blind under SHARED drift (corr 0.19, 'confidently wrong'); it DRIVES emergent Bayesian cue re-weighting (slope 0.65 vs blind 0.09 -- the reliability law agent_cue_integration.py left open) and a re-anchor switch that follows the BELIEF not the truth (inflate rho -> +0.34 landmark trust vs blind +0.00). GAPS.md #7
run src.eval.curved_path_integration --seeds 5      # NON-EUCLIDEAN PATH INTEGRATION (Gauss-Bonnet; complements grid_3d.py's bat 3-D volume code): a flat grid/head-direction integrator DETECTS curvature from self-motion -- the parallel-transport holonomy around a closed loop equals enclosed AREA x CURVATURE (= solid angle; slope 1.00, corr 1.00, residual 1.3%), a geodesic triangle with 3 right angles gives pi/2; EXACTLY 0 in flat space (loops close), grows as 1/R^2; a flat compass then mis-homes by the holonomy (1.98 curved vs 0.03 flat). The non-Euclidean analogue of grid shearing. GAPS.md #5g
run src.eval.systems_consolidation --seeds 5        # SYSTEMS CONSOLIDATION / CLS (McClelland 1995; Squire-Alvarez 1995; Frankland-Bontempi 2005): replay transfers maps from a fast HIPPOCAMPAL one-shot store into the slow CORTICAL (LLM-analogue) weights -> temporally-GRADED retrograde amnesia (cortex-only recall: remote 0.61 vs recent 0.23, gradient +0.39, corr 0.87), gradient appears ONLY on lesion (intact 100% all ages), and VANISHES without replay (remote 0.13 chance, gradient +0.02) -> the familiar map ends up in the cortical weights, hippocampus-independent. GAPS.md #8
run src.eval.active_inference --seeds 5             # ACTIVE INFERENCE / EPISTEMIC FORAGING (Friston): agent rewarded ONLY for reaching the goal (NO landmark/info-gain/exploration reward) -- the platform physics is the #7 uncertainty (drift grows u, landmark resets it, goal-commit succeeds with P(u)). A belief planner AND a model-free Q-learner EMERGENTLY detour to a landmark to relocalise when uncertain (52% / 82% of starts); NO-DRIFT world -> 0% detour (proof it's uncertainty-driven, not hardcoded); planner 47% vs sigma-blind greedy 21% vs random 4%; u-blind ablation collapses to 20%. GAPS.md #9
run src.eval.interoceptive_map --seeds 5           # INTEROCEPTIVE ANCHORING (Kennedy-Shapiro 2009; Keramati-Gutkin 2014): NO 'thirsty->water' rule -- only a homeostatic reward -(t^2+h^2) and the body (deficits grow, water resets thirst, food resets hunger). A belief planner over (pos,t,h) EMERGENTLY navigates to the drive-matched resource (96% vs 0% for a drive-BLIND planner), REMAPS value with drive (thirsty-vs-hungry value residual corr -0.93; resource value tracks its own deficit +0.29), and keeps the body regulated (mean drive 57 vs blind 180 vs random 152), shuttling 11x/life. The map is anchored to the body. GAPS.md #10
run src.eval.neurogenesis_stamp --seeds 5          # ADULT NEUROGENESIS (Aimone-Wiles-Gage 2006/2009; Kee 2007; Rangel 2014): NO time encoded, content random -- only the mechanism (a young cohort of cells is born each step, hyper-excitable+hyper-plastic, then freezes). EMERGES: TEMPORAL STAMPING (code overlap tracks temporal proximity, corr -0.60, near/far AUC 0.96 vs static 0.50 -- the stamp is the cohort, not content) + REDUCED INTERFERENCE (old memories retained 0.44 vs static 0.31, recall FLAT across age gap -0.01 vs static catastrophic recency +0.52). Static DG (no turnover) shows neither. GAPS.md #11
run src.eval.unified_agent --seeds 5               # INTEGRATION CAPSTONE -- the organs act as ONE machine: a single agent whose only objective is to SURVIVE composes grid position (#7/#8) + uncertainty read-out (#7) + landmark relocalisation (#1) + interoceptive drives (#4). N-ORGAN LESION DISSOCIATION (intact mean drive 36; -grid 71 catastrophic, -uncertainty 45, -landmark 45, -drive 42 -- all load-bearing, each fails its own way) + EMERGENT complementarity (the uncertainty organ is worth +8 WITH landmarks but +0 without -- the organs form a circuit, not a pile). Nothing hardcoded; which resource + when to relocalise emerge from staying alive. GAPS.md integration capstone
run src.eval.unified_agent_cortex --seeds 5        # INTEGRATION CAPSTONE, GROUNDED on the REAL grid cortex: same emergent survival policy, but position is DECODED from the real drifting _HexGridModules grid code and uncertainty is the real #7 reconstruction residual (no counters). The three POSITION organs dissociate cleanly (intact drive 48; -grid 69, -uncertainty 60, -landmark 66) and the uncertainty x landmark complementarity survives grounding (+12 with landmarks, -3 without). Honest limit: the interoceptive DRIVE organ (resource CHOICE, load-bearing in #4) barely moves survival here (46~48) -- with two symmetric resources non-adaptive alternation nearly suffices -- so grounding is a clean 3-organ dissociation, not 4. GAPS.md integration capstone (grounded)
run src.eval.unified_agent_learn --seeds 5         # INTEGRATION CAPSTONE, LEARNING: the agent LEARNS its world instead of planning in it -- dropped in NOT knowing where resources are, it discovers them and builds a value map from experience (nothing hardcoded). (A) it learns: drive 56->46 over the lifetime; (B) REPLAY (#6) propagates each discovery across the map so it's learned fast (map accuracy 1.00 with replay vs 0.66 without, a fixed window after discovery; honest: this speeds MAP-learning, not survival drive, since discovery is the bottleneck); (C) CLS (#2) consolidates the map into a slow store so a familiar world survives a hippocampal lesion (drive 47 with vs 65 without). Memory organs do their jobs in the behaving agent. GAPS.md integration capstone (learning)
run src.eval.topdown_feedback --seeds 5           # RECIPROCAL LOOP / TOP-DOWN FEEDBACK (Dupret 2010; Kentros 2004; Reynolds-Heeger): the pipeline is read-only (spatial->LLM); this adds the missing LLM->cortex feedback -- a top-down gain modulation of the spatial cortex under a conserved attention BUDGET, trained ONLY for goal-directed precision (no 'enhance the goal' rule). EMERGES: goal OVER-REPRESENTATION (corr gain vs goal-proximity +0.29, never in loss); the loop BEATS a feedforward read-only model near the goal (0.030 vs 0.057); attention TRADE-OFF (near 0.030 vs far 0.122); WRONG-goal falsifier collapses it (0.128). GAPS.md #12
run src.eval.credit_assignment --seeds 5            # CREDIT ASSIGNMENT w/o BACKPROP (Lillicrap 2016; Sacramento 2018; Payeur 2021): a deep spatial module trained by FEEDBACK ALIGNMENT (fixed random backward path, no weight transport) reaches backprop's decode + representation; the forward weights ALIGN to the feedback (grad-align >0 vs shuffled ~0); shuffling the feedback each step collapses learning (falsifier). GAPS.md Tier 5 #A1
run src.eval.meta_learning     --seeds 5            # META-LEARNING / SELF-TUNED LEARNING RATE (Behrens 2007; Wang 2018): a GRU meta-trained ONLY to predict the next obs develops, in frozen recurrent dynamics, a learning rate that RISES with volatility and FALLS with stochasticity (the dissociation, despite highest variance) -- untrained-flat control, beats best fixed-alpha. GAPS.md Tier 5 #B3. (slow: trains 5 nets)
run src.eval.astrocyte_plasticity --seeds 8         # ASTROCYTE-GATED SLOW PLASTICITY (Williamson 2024): a slow glial gate on e-prop that throttles importance-tagged synapses cuts forgetting on a continual stream, beating a UNIFORM reduction at MATCHED plasticity (targeting, not less learning) -- needs the SLOW timescale (fast-astro falsifier ~0); honest recency trade-off; kin to EWC/SI. GAPS.md Tier 5 #B4
run src.eval.emergent_grid_bio --seeds 5            # FAITHFULNESS CAPSTONE (Murray 2019 RFLO + A1 feedback alignment): the REAL path-integration grid cortex trained by a LOCAL no-weight-transport rule (eligibility x fixed random feedback, no BPTT) learns path integration AND grows the emergent periodic grid code (~backprop), never in the loss; shuffled-feedback falsifier falls to the untrained floor. The core itself learns biologically. GAPS.md Tier 5 capstone
run src.eval.complex_synapse   --seeds 5            # MULTI-TIMESCALE SYNAPSE (Benna-Fusi 2016): a synapse built as a CHAIN of coupled variables at geometric timescales forgets as a POWER LAW (log-log straight, slope ~-0.5 = 1/sqrt(t)) where a leaky SCALAR forgets EXPONENTIALLY (semilog straight); 3.3x longer memory at matched initial SNR; lifetime grows with chain depth. Graceful forgetting from the synapse. GAPS.md Tier 5 #B2
run src.eval.representational_drift --seeds 5       # REPRESENTATIONAL DRIFT / CONSERVED GEOMETRY (Morales 2025): at MATCHED single-cell drift, a LABEL-FREE geometry read-out (manifold ordering) survives geometry-PRESERVING drift (field relocation, even a FULL remap) but fails geometry-DESTROYING drift (high-D noise); held-out supervised decode confirms (not overfit); fixed decoder fails. Geometry survives, not cells. (Non-circular rebuild after a red-team killed a first version.) GAPS.md Tier 5 #C6
run src.eval.sleep_consolidation --seeds 5          # SLEEP TRIPLE-COUPLING (Latchoumane 2017; Diekelmann & Born 2010): SO->spindle->ripple nesting makes consolidation SELECTIVE (tagged fraction 0.99 vs proportional floor 0.77 -- winner-take-all over SCARCE windows, EMERGENT not imposed) and TIMED (coupled 1.0 vs random-timed 0.5 at matched replay count); no-SO falsifier collapses selectivity to the floor. Measured, never in the loss. GAPS.md Tier 5 #C7
run src.eval.conceptual_grid_cortex --seeds 5       # CONCEPTUAL GRID CPU DE-RISK for #8 (Constantinescu/Behrens 2016): the FROZEN space cortex exposes a genuine 2-D metric a 1-D code can't -- OFF-AXIS "closer" 0.65>chance (1-D code <=0.5 there by construction), shuffled 0.50; held-out linear decode 0.63 vs 3.4 shuffled spacing. Validates the T4 cell (notebooks/m8 + src/training/train_conceptual.py) BEFORE the GPU run. GAPS.md Tier 3 #8
run src.eval.social_grid_cortex --seeds 5           # SOCIAL GRID CPU DE-RISK for #9 (Tavares 2015; Park-Miller 2021): the FROZEN space cortex exposes a DISSOCIABLE 2-D social map -- DOMINANCE from the power axis 0.96, axis dissociation +0.51 (power->dom 0.96 vs affil->dom 0.45), social-distance off-axis 0.65; shuffled collapses dominance to 0.44. Validates the T4 cell (notebooks/m9 + src/training/train_social.py). GAPS.md Tier 3 #9
run src.eval.predictions       --seeds 3            # §7 HYPOTHESIS GENERATOR: falsifiable predictions (content->conjunctive; spatial-noise->pure-time)
run src.eval.agent_navigation  --seeds 5            # BEHAVING AGENT: closed-loop navigation emerges + self-learned SR map -> flexible zero-shot any-goal nav
run src.eval.agent_memory      --seeds 5            # BEHAVING AGENT: one-shot place learning (episodic store); lesion abolishes it (Morris water maze)
run src.eval.agent_timing      --seeds 3            # BEHAVING AGENT: interval-timed action (time cells); lesion abolishes timing (reward 0.88->0.00)
run src.eval.agent_unified     --seeds 3            # BEHAVING AGENT: ONE task needs space+memory+time; clean triple-lesion dissociation (99% -> 0/0/0)
run src.eval.agent_grid_cortex --seeds 3            # BEHAVING AGENT on the REAL grid cortex: velocity-driven hex grid modules path-integrate -> nonlinear readout -> vector nav; triple dissociation on the grid substrate
run src.eval.agent_grid_drift  --seeds 3            # GRID DRIFT + CORRECTION: noisy self-motion drifts the grid estimate (unbounded); boundary-vector cells reset it near walls (Hardcastle 2015) -> localization bounded + foraging rescued
run src.eval.agent_cue_integration --seeds 3        # OPTIMAL CUE INTEGRATION: a learned fuser (no hand-coded gate) discovers near-optimal Bayesian combination of grid-PI + boundary cues -> beats either cue alone, sits on the optimal bound (Nardini 2008)
run src.eval.head_direction    --seeds 5            # HEAD-DIRECTION ORGAN: HD cells + a ring attractor EMERGE from angular path integration; heading-dominated drift driven by the HD system, bounded by a visual reset (Knierim 1995)
run src.eval.agent_deadreckoning --seeds 3          # DEAD-RECKONING BRAIN: unified HD->grid->place stack from self-motion alone; heading drift propagates to position drift; both allothetic corrections needed; homing abolished by lesioning HD or grid
run src.eval.basal_ganglia     --seeds 3            # TIER-2 SYSTEM: basal-ganglia Go/NoGo action selection; dopamine lesion abolishes learning (100->35%)
run src.eval.grid_capacity     --seeds 5            # WHY GRID CELLS: coding capacity (Fiete) via Fisher info -- grid resolution flat vs arena, place linear (33x at scale); + honest linear-decode caveat
run src.eval.grid_catastrophe   --seeds 5            # CATASTROPHIC ERRORS (Fiete other half): multi-module grid code suppresses catastrophic decode jumps exponentially with module count; bimodal error law; grid dominates place at matched budget
run src.eval.reference_frame   --seeds 5            # MULTI-REFERENCE-FRAME MAP: egocentric object-vector cells (Hoydal 2019) + grid REANCHORING to an object frame; object-relative goal (moving object) solved by object-frame agent, not global; grid translates with the object
run src.eval.plane_of_motion  --seeds 5            # 3D PLANE-OF-MOTION (bat 2026): 2D grid aligned to the PCA-estimated motion plane + off-plane code; orientation-invariant 3D localization; fixed-plane grid fails at steep tilt (honest: no clean win vs naive 3D grid)
run src.eval.landmark_anchoring --seeds 3        # DYNAMIC REFERENCE-FRAME ANCHORING: reliability-gated reanchoring of the grid phase to a landmark (anchor - R(heading)@ego); corrects allocentric drift; allocentric + egocentric codes coexist (MEC 2025)
run src.eval.agent_multiframe  --seeds 3         # UNIFIED MULTI-REFERENCE-FRAME AGENT: ONE brain navigates GLOBAL (grid) AND OBJECT (object-vector+HD) frames; clean double dissociation (-grid kills global, -object kills object, -HD kills both)
run src.eval.theta_sweep     --seeds 5            # THETA-CYCLE LOOK-AROUND (Vollan 2025): online grid sweeps as active look-ahead (alternating L/R, ~20%-spacing, multi-scale); sampling space AHEAD avoids dead-ends a reactive agent enters (76->100%)
run src.eval.theta_sweep_readout --seeds 5         # THETA-SWEEP TOKENS ARE LOAD-BEARING (readout/LLM side): in a NOVEL per-episode layout a readout predicts the hazard AHEAD from real sweep tokens (90%) but collapses to chance when they are ablated or wrong-heading-shuffled; TrajectoryLLM(use_theta_sweep=True) feeds these (full frozen-LLM ablation: notebooks/m7_theta_sweep_llm_kaggle.py)
run src.eval.egocentric_anchors --seeds 5         # COEXISTING EGOCENTRIC ANCHORS (Nat Commun 2025): egocentric center + object + boundary frames coexist (decode all from the combined population), each specific to its own cells; adds EgocentricCenterCells
run src.eval.local_3d_order   --seeds 5            # LOCAL 3D ORDER not a global lattice (bat MEC): a local-order (blue-noise) field code has high local order but low global lattice -- separable from a true 3D lattice and from random
run src.eval.agent_grid_reanchor --seeds 5         # OBJECT REANCHORING IN THE CORE CORTEX: object-vector cells reanchor the grid phase from INSIDE _HexGridModules.forward(object_obs=) via a shared ego->allo transform; object cue rescues open-field drift where boundaries can't; shuffled-anchor control fails (load-bearing integration)
run src.eval.grid_3d          --seeds 5            # BIOLOGICALLY-GROUNDED 3D GRID CODE (bat MEC; Ginosar 2021): LocalOrder3DGrid wired into _HexGridModules(grid_3d=True) replaces the 1D-z stub -- fields in the bat regime (local order, NO global lattice) vs a cubic-lattice control; path-integrates + localizes in full 3D
run src.eval.content_binding   --seeds 6           # §7 content-binding (what-where-when): conjunctive vs pure time cells + decode what & when (bat CA1 2023)

if [ "${1:-}" = "exploratory" ]; then
  echo; echo "############ EXPLORATORY demos (illustrative; not the central claims) ############"
  for m in emergence boundary_anchoring pillars planning goal_navigation relational continual embodiment generalize_trajectory magnitude_frontier; do
    if python - "$m" <<'PY' 2>/dev/null; then
import importlib.util, sys
sys.exit(0 if importlib.util.find_spec("src.eval." + sys.argv[1]) else 1)
PY
      run "src.eval.$m" || echo "  (skipped src.eval.$m — non-zero exit)"
    fi
  done
fi

echo; echo "############ LANGUAGE results (GPU) ############"
echo "Run on a single T4 (not here): notebooks/m2_extrapolation_multiseed_kaggle.py (multi-seed grid vs place),"
echo "and notebooks/m2_grid_cortex_all_tasks_kaggle.py. See REPRODUCE.md for the figure->command map."
echo "CAPSTONE: notebooks/m5_deadreckoning_llm_kaggle.py -- a frozen LLM reads the emergent HD+grid neural"
echo "  code to answer self-localization (WHERE + egocentric HOME vector); cortex-ON vs text-only-OFF, n=6."
echo; echo "DONE — see results/*.json and results/*.svg"
