#!/usr/bin/env bash
# reproduce_all.sh — regenerate every CPU result/figure behind the paper from scratch.
#
# Verified environment: Python 3.11, torch 2.2.2 (CPU is fine), numpy (1.26+ or 2.x both work; a
# harmless NumPy-1.x/2.x import warning may print). No GPU needed for any of the MAIN experiments
# below; the LANGUAGE results (Qwen + LoRA) run on a single T4 via notebooks/ (see bottom).
#
#   bash reproduce_all.sh            # MAIN experiments at the paper's seed counts
#   SEEDS=3 bash reproduce_all.sh    # quicker pass (fewer seeds)
#   bash reproduce_all.sh exploratory  # also run the single-run demo pillars
#
# Each command writes results/<name>.json (+ .svg). Artifacts are committed, so a clean run should
# reproduce the committed numbers within seed noise.
set -euo pipefail
cd "$(dirname "$0")"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-4}"
SEEDS="${SEEDS:-8}"          # stats/extrapolation paper runs use 8; characterization uses 5
SEEDS5="${SEEDS5:-5}"

run () { echo; echo "=== $* ==="; python -u -m "$@"; }

echo "############ MAIN experiments (multi-seed, paper figures) ############"
run src.eval.stats             --seeds "$SEEDS"     # §6 cognitive suite: planning/value/relational/continual
run src.eval.extrapolation     --seeds "$SEEDS"     # Fig 1: length extrapolation vs fair place/GRU/oracle
run src.eval.ablations         --seeds "$SEEDS5"    # Fig 2a: range/scale/training-dist/sequence-model ablations
run src.eval.seq_baselines     --seeds "$SEEDS5"    # Fig 2b: fair Transformer baselines (the honest tie)
run src.eval.code_necessity    --seeds "$SEEDS5"    # Fig 3: capacity + remapping (where the code wins)
run src.eval.multimap_task     --seeds "$SEEDS5"    # boundary: remapping doesn't help a trained model w/ context-id
run src.eval.frontier_probes   --seeds "$SEEDS5"    # Fig 4: sample efficiency + noise (honest non-wins)
run src.eval.controls          --seeds "$SEEDS5"    # mechanism vs parameters control
run src.eval.significance      --n_fast 20 --n_slow 8   # paired tests (p-values) on every headline claim; resumable
run src.eval.torus             --seeds "$SEEDS"     # non-Euclidean (torus): periodicity NECESSARY, breaks the tie + leakage rebuttal
run src.eval.structural_transfer --seeds "$SEEDS"   # TEM: frozen space-trained metric -> relational inference (+ falsifiers)
python -u -m src.eval.phase_diagram   # SYNTHESIS: when each inductive bias wins (reads the JSONs above; no training)
run src.eval.successor         --seeds "$SEEDS"     # §7 predictive map (SR): plans detours where geometry stalls; geodesic fields; TD-learned
run src.eval.time_cells        --seeds "$SEEDS"     # §7 temporal map: time cells + scalar (Weber) timing EMERGE from a trained recurrent substrate (vs untrained control)
run src.eval.spiking_time_cells --seeds 6           # §7 SPIKING + multi-timescale: spiking time cells + emergent tau-spectrum that aids timing (vs homogeneous-tau control)
run src.eval.eprop_local_learning --seeds 5         # §7 LOCAL LEARNING: time cells emerge under e-prop (eligibility traces, NO backprop) -- the brain's learning rule
run src.eval.btsp              --seeds 5            # §7 BTSP one-shot learning (Bittner 2017): one plateau imprints a place field in ONE pass via a seconds-wide asymmetric kernel; field shifts UPSTREAM (predictive), shift scales with speed; needs seconds-scale + asymmetry (vs STDP/symmetric controls). GAPS.md #1
run src.eval.space_time_circuit --seeds 5           # §7 CIRCUIT EMBEDDING: place + time + conjunctive space-time cells coexist in ONE circuit (Neuron 2024)
run src.eval.social_space      --seeds 5            # SOCIAL SPACE (Danjo 2018, Omer 2018): one substrate fed self + OTHER-agent motion develops pure self-place + pure other-place cells (emergent, eta^2); self/other lesion double dissociation. GAPS.md #4
run src.eval.goal_vector       --seeds 5            # GOAL-VECTOR CODE (Sarel 2017; Banino 2018): a policy trained ONLY to reach randomized goals develops a goal-DIRECTION code (emergent, goal-specific vs untrained + shuffle nulls); honest scope (allocentric/redundant; ego+distance don't emerge). GAPS.md #3A
run src.eval.reward_map        --seeds 5            # REWARD MAP (Hollup 2001; Gauthier-Tank 2018): reward-triggered BTSP builds place fields that ANTICIPATE the goal (upstream shift, vanishes with symmetric kernel) + reward-specific over-representation (vs yoked-random control). GAPS.md #3B
run src.eval.hexadirectional   --seeds 5            # HEXADIRECTIONAL / GRID CODE FOR CONCEPTS (Doeller 2010; Constantinescu 2016): hex grid -> 6-fold direction signal via a movement nonlinearity (conjunctive grid x direction); symmetry INHERITED from the lattice (square -> 4-fold), linear read-out flat -> not circular. GAPS.md #2
run src.eval.neuromodulation   --seeds 5            # NEUROMODULATION (Hasselmo 2006; Yu-Dayan 2005): ACh sets encode/retrieve on a CA3 auto-associator -> high-ACh encoding blocks OVERLAP-SPECIFIC intrusion of an old memory at MATCHED write energy (recurrent contamination, not non-storage), completion needs W_rec; NE surprise = NOVELTY not change (AUC~1) and a surprise remap is adaptive two-sided (learns new env + protects old) vs a matched no-reset control. GAPS.md #5
run src.eval.hippocampal_subfields --seeds 5        # DG PATTERN SEPARATION + CA1 COMPARATOR (Marr 1971; Treves-Rolls 1994; Lisman-Grace 2005): a sparse DG expansion lets CA3 recall M=24 SIMILAR environments (0.87) where a MATCHED-SIZE dense expansion interferes (0.37, worse than not expanding -> sparsity is load-bearing, not dimensionality); separation index 0.54 vs 1.00; CA1 mismatch detects novelty (AUC 1.00) and collapses to chance (0.50) when the CA3 memory stream is ablated -> a genuine entorhinal-vs-memory comparator. Measured, never in a loss. GAPS.md #5b
run src.eval.ephaptic_coupling --seeds 5            # EPHAPTIC COUPLING (Anastassiou-Koch 2011; Chiang-Durand 2019): a self-generated ZERO-MEAN field synchronizes LIF spike TIMING (chi 1.00 vs 0.07) at MATCHED firing rate (|d rate| 0.03 -> timing not drive) where matched-budget SPARSE synapses cannot (0.11); dose-response transition; zeroing the field -> baseline; the synchrony drives a downstream coincidence detector (0.22 vs 0.01) at matched rate. A non-synaptic channel doing computational work. GAPS.md #5c
run src.eval.grid_shearing --seeds 5                # GRID SHEARING (Krupic 2015; Stensola 2015): the hexagonal grid stays hexagonal in a SQUARE (gridness 1.00) but SHEARS in a TRAPEZOID under the same boundary anchoring (0.01) -- EMERGENT, the deformation is never drawn, it falls out of the square-calibrated boundary fix mislocalizing in a non-square arena; dose-response with shear; DOUBLE-DISSOCIATION falsifier (trapezoid+no-anchor 1.14 and square+anchor 1.00 both stay hexagonal -> deformation needs BOTH geometry and anchoring). GAPS.md #5d
run src.eval.manifold_geometry --seeds 5          # MANIFOLD DEFORMATION (deeper #5d; Gardner 2022): #5d showed the RATE MAP shears -- does the NEURAL MANIFOLD itself deform, or stay a rigid torus? (A) trapezoid grid codes lie on the SAME manifold as the square's (overlap 0.88 vs reference 0.90; deformation +0.02~0) -> RIGID torus, so #5d is a space->manifold MAP warping, not a manifold deformation. (B) in a BARRIER (non-Euclidean) env the fixed grid ignores the wall (geodesic-advantage +0.02) while a PLASTIC code reshapes to the geodesic geometry (+0.27) -> manifold deformation REQUIRES plasticity, which the rigid CAN lacks. GAPS.md #5d (deeper)
run src.eval.reference_transform --seeds 5          # RSC/PPC EGO->ALLO TRANSFORM (Andersen-Zipser 1988; Byrne-Becker-Burgess 2007): a plain MLP trained ONLY on allocentric output learns the head-direction-gated rotation -- generalizes to head directions HELD OUT of training (RMSE 0.07, 4% of scale) so it is the transform not a lookup; GAIN-FIELD units emerge (27%, multiplicative ego*HD, extra-R2 0.08 vs 0.015 untrained -- Zipser-Andersen, never in the loss); shuffled-HD (0.90) and no-HD (2.24>scale) falsifiers explode. GAPS.md #5e
run src.eval.astrocyte_syncytium --seeds 5          # ASTROCYTE SYNCYTIUM (Scemes-Giaume 2006; Henneberger 2010): gap-junction Ca2+ spread binds a silent-but-surrounded synapse heterosynaptically (gate 0.95 vs 0.00 point-wise) and gates plasticity by SPATIAL DENSITY (clustered core 0.40 vs matched-count scattered 0.07); UNCOUPLED does nothing at sub-threshold drive, and a fully REGENERATIVE wave FLOODS (1.00 vs 1.00, no selectivity) -> the computation is the GRADED spread, not the wave. Honest: effect real but modest. GAPS.md #5f
run src.eval.replay_planning   --seeds 8            # REPLAY THAT COMPUTES (Foster-Wilson 2006; Pfeiffer-Foster 2013; Mattar-Daw 2018): a direction-free SCALAR priority (|TD error|, prioritized sweeping) makes value sweep BACKWARD from the reward -- reverse replay = credit assignment (reverse-frac 1.00 vs 0.50 random, p=0.009), direction NEVER encoded; the SAME map read forward = a planning rollout that routes around a barrier (100% vs 1% untrained); one value rule, opposite directions (Diba-Buzsaki dissociation); prioritized reaches a plannable map 16x fewer backups than random. GAPS.md #6
run src.eval.uncertainty_behavior --seeds 5         # UNCERTAINTY DRIVES BEHAVIOR (Ma 2006; Ernst-Banks 2002; Sreenivasan-Fiete 2011): a CALIBRATED uncertainty read from the grid population (reconstruction residual = inter-module inconsistency) is calibrated to true decode error under INDEPENDENT module drift (corr 0.87), rises 2.5x with path integration, resets at a cue -- but blind under SHARED drift (corr 0.19, 'confidently wrong'); it DRIVES emergent Bayesian cue re-weighting (slope 0.65 vs blind 0.09 -- the reliability law agent_cue_integration.py left open) and a re-anchor switch that follows the BELIEF not the truth (inflate rho -> +0.34 landmark trust vs blind +0.00). GAPS.md #7
run src.eval.curved_path_integration --seeds 5      # NON-EUCLIDEAN PATH INTEGRATION (Gauss-Bonnet; complements grid_3d.py's bat 3-D volume code): a flat grid/head-direction integrator DETECTS curvature from self-motion -- the parallel-transport holonomy around a closed loop equals enclosed AREA x CURVATURE (= solid angle; slope 1.00, corr 1.00, residual 1.3%), a geodesic triangle with 3 right angles gives pi/2; EXACTLY 0 in flat space (loops close), grows as 1/R^2; a flat compass then mis-homes by the holonomy (1.98 curved vs 0.03 flat). The non-Euclidean analogue of grid shearing. GAPS.md #5g
run src.eval.systems_consolidation --seeds 5        # SYSTEMS CONSOLIDATION / CLS (McClelland 1995; Squire-Alvarez 1995; Frankland-Bontempi 2005): replay transfers maps from a fast HIPPOCAMPAL one-shot store into the slow CORTICAL (LLM-analogue) weights -> temporally-GRADED retrograde amnesia (cortex-only recall: remote 0.61 vs recent 0.23, gradient +0.39, corr 0.87), gradient appears ONLY on lesion (intact 100% all ages), and VANISHES without replay (remote 0.13 chance, gradient +0.02) -> the familiar map ends up in the cortical weights, hippocampus-independent. GAPS.md #8
run src.eval.active_inference --seeds 5             # ACTIVE INFERENCE / EPISTEMIC FORAGING (Friston): agent rewarded ONLY for reaching the goal (NO landmark/info-gain/exploration reward) -- the platform physics is the #7 uncertainty (drift grows u, landmark resets it, goal-commit succeeds with P(u)). A belief planner AND a model-free Q-learner EMERGENTLY detour to a landmark to relocalise when uncertain (52% / 82% of starts); NO-DRIFT world -> 0% detour (proof it's uncertainty-driven, not hardcoded); planner 47% vs sigma-blind greedy 21% vs random 4%; u-blind ablation collapses to 20%. GAPS.md #9
run src.eval.interoceptive_map --seeds 5           # INTEROCEPTIVE ANCHORING (Kennedy-Shapiro 2009; Keramati-Gutkin 2014): NO 'thirsty->water' rule -- only a homeostatic reward -(t^2+h^2) and the body (deficits grow, water resets thirst, food resets hunger). A belief planner over (pos,t,h) EMERGENTLY navigates to the drive-matched resource (96% vs 0% for a drive-BLIND planner), REMAPS value with drive (thirsty-vs-hungry value residual corr -0.93; resource value tracks its own deficit +0.29), and keeps the body regulated (mean drive 57 vs blind 180 vs random 152), shuttling 11x/life. The map is anchored to the body. GAPS.md #10
run src.eval.neurogenesis_stamp --seeds 5          # ADULT NEUROGENESIS (Aimone-Wiles-Gage 2006/2009; Kee 2007; Rangel 2014): NO time encoded, content random -- only the mechanism (a young cohort of cells is born each step, hyper-excitable+hyper-plastic, then freezes). EMERGES: TEMPORAL STAMPING (code overlap tracks temporal proximity, corr -0.60, near/far AUC 0.96 vs static 0.50 -- the stamp is the cohort, not content) + REDUCED INTERFERENCE (old memories retained 0.44 vs static 0.31, recall FLAT across age gap -0.01 vs static catastrophic recency +0.52). Static DG (no turnover) shows neither. GAPS.md #11
run src.eval.unified_agent --seeds 5               # INTEGRATION CAPSTONE -- the organs act as ONE machine: a single agent whose only objective is to SURVIVE composes grid position (#7/#8) + uncertainty read-out (#7) + landmark relocalisation (#1) + interoceptive drives (#4). N-ORGAN LESION DISSOCIATION (intact mean drive 36; -grid 71 catastrophic, -uncertainty 45, -landmark 45, -drive 42 -- all load-bearing, each fails its own way) + EMERGENT complementarity (the uncertainty organ is worth +8 WITH landmarks but +0 without -- the organs form a circuit, not a pile). Nothing hardcoded; which resource + when to relocalise emerge from staying alive. GAPS.md integration capstone
run src.eval.unified_agent_cortex --seeds 5        # INTEGRATION CAPSTONE, GROUNDED on the REAL grid cortex: same emergent survival policy, but position is DECODED from the real drifting _HexGridModules grid code and uncertainty is the real #7 reconstruction residual (no counters). The three POSITION organs dissociate cleanly (intact drive 48; -grid 69, -uncertainty 60, -landmark 66) and the uncertainty x landmark complementarity survives grounding (+12 with landmarks, -3 without). Honest limit: the interoceptive DRIVE organ (resource CHOICE, load-bearing in #4) barely moves survival here (46~48) -- with two symmetric resources non-adaptive alternation nearly suffices -- so grounding is a clean 3-organ dissociation, not 4. GAPS.md integration capstone (grounded)
run src.eval.unified_agent_learn --seeds 5         # INTEGRATION CAPSTONE, LEARNING: the agent LEARNS its world instead of planning in it -- dropped in NOT knowing where resources are, it discovers them and builds a value map from experience (nothing hardcoded). (A) it learns: drive 56->46 over the lifetime; (B) REPLAY (#6) propagates each discovery across the map so it's learned fast (map accuracy 1.00 with replay vs 0.66 without, a fixed window after discovery; honest: this speeds MAP-learning, not survival drive, since discovery is the bottleneck); (C) CLS (#2) consolidates the map into a slow store so a familiar world survives a hippocampal lesion (drive 47 with vs 65 without). Memory organs do their jobs in the behaving agent. GAPS.md integration capstone (learning)
run src.eval.topdown_feedback --seeds 5           # RECIPROCAL LOOP / TOP-DOWN FEEDBACK (Dupret 2010; Kentros 2004; Reynolds-Heeger): the pipeline is read-only (spatial->LLM); this adds the missing LLM->cortex feedback -- a top-down gain modulation of the spatial cortex under a conserved attention BUDGET, trained ONLY for goal-directed precision (no 'enhance the goal' rule). EMERGES: goal OVER-REPRESENTATION (corr gain vs goal-proximity +0.29, never in loss); the loop BEATS a feedforward read-only model near the goal (0.030 vs 0.057); attention TRADE-OFF (near 0.030 vs far 0.122); WRONG-goal falsifier collapses it (0.128). GAPS.md #12
run src.eval.map_value_decouple --seeds 8         # MAP/VALUE DECOUPLING (Dayan 1993; Momennejad 2017): the SR decouples the goal-INDEPENDENT cognitive map M (hippocampal state-space) from VALUE (V=M*R, striatal). ONE map serves 8 goals (reuse 1.00); when the goal MOVES the decoupled agent REVALUES INSTANTLY (V=M[:,g_new], success 1.00) where a FUSED agent (value baked into the state) stays stuck on the old goal (0.15, paired p=0.016); the fused agent must RELEARN (15 value-iteration sweeps) vs 0 for the decoupled. Separating 'where I am' from 'what it's worth' is the payoff. GAPS.md #13
run src.eval.superposition_capacity --seeds 5     # POLYSEMANTIC SUPERPOSITION (Elhage 2022): a localized one-cell-per-place code is monosemantic (N cells <= N fields), but intracranial data show hippocampal cells are POLYSEMANTIC. Build only the mechanism (tied autoencoder bottleneck) + task (reconstruct a SPARSE field vector, one place at a time, from F=4N fields). EMERGES: 32 cells recall ALL 128 fields (4x more environments than cells, vs monosemantic ceiling 0.25); each cell polysemantic (4.5 fields); FALSIFIER -- DENSE activity collapses recall to 0.49 (dose-response 1.00->1.00->0.52). Superposition is bought by sparsity, not imposed. GAPS.md (superposition)
run src.eval.small_world_search --seeds 5         # SMALL-WORLD SEARCHABILITY (Kleinberg 2000): a pure lattice crawls; real connectivity is small-world, but short paths EXISTING isn't enough -- a decentralised searcher (local links + goal proximity, no global oracle) can only FIND them if the shortcut exponent P(r)~r^-a is navigable. Build only the mechanism (lattice + candidate long-range links from a FLAT prior + use-based selection under a 1-link/node budget) + task (greedy routing). EMERGES: (A) delivery is an INTERIOR optimum in a (a=0 19.8, a=1 18.1, a=2 21.1, a=3 34.7; too-local a=3 scales x1.47 vs x1.28); (B) findability -- flat prior has SHORTEST true paths (6.87) but WORST stretch (2.86), emergent cuts to 2.33; (C) use-selection grows a: 0->1.39+-0.01 (navigable band), delivery 16.5 beats flat 19.8 AND best fixed 18.1; (D) FALSIFIER random-prune stays a=-0.01, delivery 19.6 (no gain). Honest: textbook a=D=2 is asymptotic, finite-size optimum is lower, emergent lands there. GAPS.md (small-world)
run src.eval.anisotropic_3d --seeds 5             # ANISOTROPIC 3D CODING (Hayman 2011): naive 2D->3D gives an ISOTROPIC lattice, but rats climbing have vertically-ELONGATED fields + impaired vertical odometry (flying bats are isotropic, Ginosar 2021). Build only ISOTROPIC hardware (isotropic code noise, isotropic init, one shared power budget) + task (capacity-limited code reconstructs 3D position from GRAVITY-BIASED experience: large horizontal, small vertical spread). Anisotropy EMERGES by water-filling: (A) normalized decode error vertical 0.50 vs horizontal 0.15 -> ratio 3.33 (coarse vertical, Hayman stripes); (B) FALSIFIER isotropic experience -> ratio 1.04 (flying regime); (C) dose-response 1.0->1.66->3.32->6.61 as vertical experience 1.0->0.6->0.3->0.15 (~1/exp, the water-filling law); (D) absolute vertical error SMALL (0.044) -- only normalized resolution reveals the loss. Nothing hardcoded. GAPS.md (anisotropic-3D)
run src.eval.semantic_warp --seeds 5              # SEMANTIC WARPING (Boccara 2019): the perforant path projects non-spatial features into grid/place cells, so the map is NOT purely geographic -- grid cells warp toward relevant locations, mixed-selective to reward AND space. Build only a code with spatial + perforant/semantic input + task (reconstruct [position, value]); the warp is never in the loss. EMERGES: (A) warp (concept|space) +0.27 WHILE spatial (space|concept) +0.62 -- a warped SPATIAL map (mixed selectivity); (B) DOUBLE-DISSOCIATION falsifier -- remove perforant path -> warp +0.00, and concept irrelevant (b=0) -> warp +0.01 (needs BOTH path and relevance); (C) dose-response +0.01->+0.08->+0.19->+0.32 as relevance b=0->2; (D) PAYOFF held-out linear probe reads concept off warped map 0.60 vs no-perforant 0.23 (chance 0.20) -- reader gets semantic-spatial structure for free. GAPS.md (semantic-warp)
run src.eval.rsc_routing --seeds 5                # BIFURCATED RSC ROUTING (Molecular Psychiatry 2024): the RSC ships TWO streams not one -- M2/action (egocentric affordance) + AD/memory (allocentric location); inactivating one impairs place-action, the other object-location. Hardcode only the two-pathway wiring; content+benefit emerge. Two conflicting demands (action=heading-EQUIVARIANT, memory=heading-INVARIANT): (A) frames DISSOCIATE -- heading R2 action head 0.82 vs memory head 0.04 (ego vs allo, never assigned); (B) selective routing -- memory pathway selectivity +0.95 (WHERE not turn) vs unified entanglement 0.76 (BOTH); (C) split ENABLES double dissociation -- kill action pathway -> action x5.5 memory x1.0, kill memory -> memory x58 action x1.0, but a UNIFIED lesion loses BOTH (+772%/+650%); (D) FALSIFIER no conflict (both allo) -> memory pathway leaks action 0.41 vs 0.01. Honest: split does NOT lower total loss -- benefit is segregation not efficiency. GAPS.md (rsc-routing)
run src.eval.intrinsic_motivation --seeds 5      # INTRINSIC MOTIVATION (agency frontier #1; Oudeyer-Kaplan 2007, Schmidhuber; Burda-Pathak 2019): the seed of autonomy -- self-directed behaviour with NO external reward and no goal. The intrinsic reward is ONLY the agent's own world-model error dynamics (learning progress = error reduction), never task reward or a hardcoded goal. EMERGES: (A) self-directed MASTERY -- learning-progress masters 77/77 learnable cells vs random 43 (drive organises exploration); (B) NOISY-TV FALSIFIER -- add irreducible-randomness sink: pure NOVELTY (error itself) is TRAPPED 31% of life, LEARNING-PROGRESS (error reduction) leaves after 10% (noise can't fake across-visit progress); (C) efficiency -- LP reaches 90% mastery in 352 steps vs novelty 437 vs random never. Honest: novelty also masters eventually; LP's edge is trap-avoidance + efficiency. Next agency organ: goal generation. GAPS.md (agency-1)
run src.eval.goal_generation --seeds 5           # GOAL GENERATION (agency frontier #2; Colas-Oudeyer 2022 autotelic agents): the agent proposes its OWN goals by learning progress over a goal space -- no handed goal, no difficulty schedule; the space has IMPOSSIBLE goals (ceiling 0, goal-space noisy TV) it must learn to avoid. EMERGES: (A) a CURRICULUM -- self-proposed goal difficulty rises 0.39->0.56 over the lifetime (easy first, hard later), never scheduled; random flat; (B) MASTERY -- autotelic masters 48/49 learnable goals vs random 40; (C) threads the ZONE OF PROXIMAL DEVELOPMENT -- 'always hardest' wastes 100% on impossible goals (masters 0), 'always easiest' stalls (masters 1), autotelic self-organises to the productive frontier (52%). Honest: random masters 40 too; the edge is the emergent curriculum + completeness. Builds on organ 1. GAPS.md (agency-2)
run src.eval.forward_model --seeds 5             # FORWARD MODEL + EFFERENCE COPY (agency frontier #3; von Holst 1950, Sperry 1950, Frith-Blakemore 2000, Wolpert): ONE self-supervised forward model (predict next sensation from sensation + efference copy) grounds BOTH the sense of self AND motor control -- no self/world label ever in the loss. Self and world perturbations are magnitude-matched, so only predictability-given-the-efference-copy separates them. EMERGES: (A) AGENCY -- self-caused error 0.003 vs world-caused 0.456, read from error alone AUC 0.97 (never labelled); (B) sensory ATTENUATION 0.01x (can't tickle yourself); (C) FALSIFIER -- remove efference copy -> self 0.46 = world 0.46, AUC 0.50 (chance); (D) DOUBLE DUTY -- same model as a Smith predictor tracks under delay where stale feedback lags (delay 0 equal 0.04; delay 6 FM 0.21 vs stale 3.51), advantage grows with delay. GAPS.md (agency-3)
run src.eval.imagination_planning --seeds 5      # IMAGINATION -> PLANNING (agency frontier #4; Tolman cognitive map, Daw model-based control, Hassabis constructive simulation): roll organ-3's one-step forward model forward = imagination; does planning emerge? Build only the imagination (roll the LEARNED model forward) + a goal + generic 'closest imagined approach' selection (MPC); NO trained policy, NO hand-coded planner. On a detour (circular obstacle) EMERGES: (A) PLANNING -- imagination-planner solves the detour 100% zero-shot; (B) MODEL-BASED not habit -- reactive go-straight 0%, and moved-goal revaluation planner 100% vs reactive 67%; (C) needs MULTI-STEP imagination -- H=1 (bare 1-step model) myopic 30%, jumps to 100% by H=4; (D) FALSIFIER -- corrupt the forward model -> planning collapses to 0% (rides on imagination accuracy). Planning is what imagination does when pointed at a goal. GAPS.md (agency-4)
run src.eval.affect_valence --seeds 5            # AFFECT / VALENCE (agency frontier #5; Eldar-Dayan 2016 mood-as-momentum): a global good/bad state (mood) that colours what matters. Build only the mechanism (mood = leaky integral of reward PREDICTION ERRORS, biasing perceived reward r_eff=r+f*tanh(mood)); swings/instability/distortion NOT put in. EMERGES: (A) mood = MOMENTUM OF SURPRISE not level -- spikes at streak onset +0.20, decays to 0 when expected, -0.20 at bad onset; (B) SELF-REINFORCING SWINGS above a critical gain -- mood std 0.03->0.05->0.64->1.41 as f=0->2->4->6, slow autocorr -0.01->+0.68 (bipolar-like cycles); (C) affect COLOURS a stationary world -- value-estimate swing 0.10->3.13 (mood distorts perceived worth); (D) FALSIFIER -- cut feedback (f=0) -> passive fast read-out, no swings. Completes the agency stack. GAPS.md (agency-5)
run src.eval.embodied_agent --seeds 5            # INTEGRATION CAPSTONE -- the agency organs as ONE autonomous machine (Stage-1 reference loop the 3D world drives): world model + imagination/planning + intrinsic motivation + goal generation + affect + localization, wired into one embodied agent in a continuous world (obstacle + water/food behind it, thirst/hunger), NO scripted goal. (A) AUTONOMOUS+COMPETENT -- full loop mean drive 1.6 (survives) vs NULL random-action 4.5 (floods); (B) each organ on its OWN axis -- planning reaches behind-obstacle goals 100% vs reactive 0%, intrinsic discovers both resources by step 197 & covers 79% vs random 435/47%, goal-gen heads to the needed resource when urgent 69% vs 0%; (C) HONEST LIMIT -- coarse survival does NOT rank individual organ ablations (coupled in a small world); each organ scored on its own axis, the clean per-organ dissociations are in the standalone evals. The organs COMPOSE into one autonomous loop. GAPS.md (integration capstone)
run src.eval.credit_assignment --seeds 5            # CREDIT ASSIGNMENT w/o BACKPROP (Lillicrap 2016; Sacramento 2018; Payeur 2021): a deep spatial module trained by FEEDBACK ALIGNMENT (fixed random backward path, no weight transport) reaches backprop's decode + representation; the forward weights ALIGN to the feedback (grad-align >0 vs shuffled ~0); shuffling the feedback each step collapses learning (falsifier). GAPS.md Tier 5 #A1
run src.eval.meta_learning     --seeds 5            # META-LEARNING / SELF-TUNED LEARNING RATE (Behrens 2007; Wang 2018): a GRU meta-trained ONLY to predict the next obs develops, in frozen recurrent dynamics, a learning rate that RISES with volatility and FALLS with stochasticity (the dissociation, despite highest variance) -- untrained-flat control, beats best fixed-alpha. GAPS.md Tier 5 #B3. (slow: trains 5 nets)
run src.eval.astrocyte_plasticity --seeds 8         # ASTROCYTE-GATED SLOW PLASTICITY (Williamson 2024): a slow glial gate on e-prop that throttles importance-tagged synapses cuts forgetting on a continual stream, beating a UNIFORM reduction at MATCHED plasticity (targeting, not less learning) -- needs the SLOW timescale (fast-astro falsifier ~0); honest recency trade-off; kin to EWC/SI. GAPS.md Tier 5 #B4
run src.eval.emergent_grid_bio --seeds 5            # FAITHFULNESS CAPSTONE (Murray 2019 RFLO + A1 feedback alignment): the REAL path-integration grid cortex trained by a LOCAL no-weight-transport rule (eligibility x fixed random feedback, no BPTT) learns path integration AND grows the emergent periodic grid code (~backprop), never in the loss; shuffled-feedback falsifier falls to the untrained floor. The core itself learns biologically. GAPS.md Tier 5 capstone
run src.eval.complex_synapse   --seeds 5            # MULTI-TIMESCALE SYNAPSE (Benna-Fusi 2016): a synapse built as a CHAIN of coupled variables at geometric timescales forgets as a POWER LAW (log-log straight, slope ~-0.5 = 1/sqrt(t)) where a leaky SCALAR forgets EXPONENTIALLY (semilog straight); 3.3x longer memory at matched initial SNR; lifetime grows with chain depth. Graceful forgetting from the synapse. GAPS.md Tier 5 #B2
run src.eval.representational_drift --seeds 5       # REPRESENTATIONAL DRIFT / CONSERVED GEOMETRY (Morales 2025): at MATCHED single-cell drift, a LABEL-FREE geometry read-out (manifold ordering) survives geometry-PRESERVING drift (field relocation, even a FULL remap) but fails geometry-DESTROYING drift (high-D noise); held-out supervised decode confirms (not overfit); fixed decoder fails. Geometry survives, not cells. (Non-circular rebuild after a red-team killed a first version.) GAPS.md Tier 5 #C6
run src.eval.sleep_consolidation --seeds 5          # SLEEP TRIPLE-COUPLING (Latchoumane 2017; Diekelmann & Born 2010): SO->spindle->ripple nesting makes consolidation SELECTIVE (tagged fraction 0.99 vs proportional floor 0.77 -- winner-take-all over SCARCE windows, EMERGENT not imposed) and TIMED (coupled 1.0 vs random-timed 0.5 at matched replay count); no-SO falsifier collapses selectivity to the floor. Measured, never in the loss. GAPS.md Tier 5 #C7
run src.eval.conceptual_grid_cortex --seeds 5       # CONCEPTUAL GRID CPU DE-RISK for #8 (Constantinescu/Behrens 2016): the FROZEN space cortex exposes a genuine 2-D metric a 1-D code can't -- OFF-AXIS "closer" 0.65>chance (1-D code <=0.5 there by construction), shuffled 0.50; held-out linear decode 0.63 vs 3.4 shuffled spacing. Validates the T4 cell (notebooks/m8 + src/training/train_conceptual.py) BEFORE the GPU run. GAPS.md Tier 3 #8
run src.eval.social_grid_cortex --seeds 5           # SOCIAL GRID CPU DE-RISK for #9 (Tavares 2015; Park-Miller 2021): the FROZEN space cortex exposes a DISSOCIABLE 2-D social map -- DOMINANCE from the power axis 0.96, axis dissociation +0.51 (power->dom 0.96 vs affil->dom 0.45), social-distance off-axis 0.65; shuffled collapses dominance to 0.44. Validates the T4 cell (notebooks/m9 + src/training/train_social.py). GAPS.md Tier 3 #9
run src.eval.predictions       --seeds 3            # §7 HYPOTHESIS GENERATOR: falsifiable predictions (content->conjunctive; spatial-noise->pure-time)
run src.eval.agent_navigation  --seeds 5            # BEHAVING AGENT: closed-loop navigation emerges + self-learned SR map -> flexible zero-shot any-goal nav
run src.eval.agent_memory      --seeds 5            # BEHAVING AGENT: one-shot place learning (episodic store); lesion abolishes it (Morris water maze)
run src.eval.agent_timing      --seeds 3            # BEHAVING AGENT: interval-timed action (time cells); lesion abolishes timing (reward 0.88->0.00)
run src.eval.agent_unified     --seeds 3            # BEHAVING AGENT: ONE task needs space+memory+time; clean triple-lesion dissociation (99% -> 0/0/0)
run src.eval.agent_grid_cortex --seeds 3            # BEHAVING AGENT on the REAL grid cortex: velocity-driven hex grid modules path-integrate -> nonlinear readout -> vector nav; triple dissociation on the grid substrate
run src.eval.agent_grid_drift  --seeds 3            # GRID DRIFT + CORRECTION: noisy self-motion drifts the grid estimate (unbounded); boundary-vector cells reset it near walls (Hardcastle 2015) -> localization bounded + foraging rescued
run src.eval.agent_cue_integration --seeds 3        # OPTIMAL CUE INTEGRATION: a learned fuser (no hand-coded gate) discovers near-optimal Bayesian combination of grid-PI + boundary cues -> beats either cue alone, sits on the optimal bound (Nardini 2008)
run src.eval.head_direction    --seeds 5            # HEAD-DIRECTION ORGAN: HD cells + a ring attractor EMERGE from angular path integration; heading-dominated drift driven by the HD system, bounded by a visual reset (Knierim 1995)
run src.eval.agent_deadreckoning --seeds 3          # DEAD-RECKONING BRAIN: unified HD->grid->place stack from self-motion alone; heading drift propagates to position drift; both allothetic corrections needed; homing abolished by lesioning HD or grid
run src.eval.basal_ganglia     --seeds 3            # TIER-2 SYSTEM: basal-ganglia Go/NoGo action selection; dopamine lesion abolishes learning (100->35%)
run src.eval.grid_capacity     --seeds 5            # WHY GRID CELLS: coding capacity (Fiete) via Fisher info -- grid resolution flat vs arena, place linear (33x at scale); + honest linear-decode caveat
run src.eval.grid_catastrophe   --seeds 5            # CATASTROPHIC ERRORS (Fiete other half): multi-module grid code suppresses catastrophic decode jumps exponentially with module count; bimodal error law; grid dominates place at matched budget
run src.eval.reference_frame   --seeds 5            # MULTI-REFERENCE-FRAME MAP: egocentric object-vector cells (Hoydal 2019) + grid REANCHORING to an object frame; object-relative goal (moving object) solved by object-frame agent, not global; grid translates with the object
run src.eval.plane_of_motion  --seeds 5            # 3D PLANE-OF-MOTION (bat 2026): 2D grid aligned to the PCA-estimated motion plane + off-plane code; orientation-invariant 3D localization; fixed-plane grid fails at steep tilt (honest: no clean win vs naive 3D grid)
run src.eval.landmark_anchoring --seeds 3        # DYNAMIC REFERENCE-FRAME ANCHORING: reliability-gated reanchoring of the grid phase to a landmark (anchor - R(heading)@ego); corrects allocentric drift; allocentric + egocentric codes coexist (MEC 2025)
run src.eval.agent_multiframe  --seeds 3         # UNIFIED MULTI-REFERENCE-FRAME AGENT: ONE brain navigates GLOBAL (grid) AND OBJECT (object-vector+HD) frames; clean double dissociation (-grid kills global, -object kills object, -HD kills both)
run src.eval.theta_sweep     --seeds 5            # THETA-CYCLE LOOK-AROUND (Vollan 2025): online grid sweeps as active look-ahead (alternating L/R, ~20%-spacing, multi-scale); sampling space AHEAD avoids dead-ends a reactive agent enters (76->100%)
run src.eval.theta_sweep_readout --seeds 5         # THETA-SWEEP TOKENS ARE LOAD-BEARING (readout/LLM side): in a NOVEL per-episode layout a readout predicts the hazard AHEAD from real sweep tokens (90%) but collapses to chance when they are ablated or wrong-heading-shuffled; TrajectoryLLM(use_theta_sweep=True) feeds these (full frozen-LLM ablation: notebooks/m7_theta_sweep_llm_kaggle.py)
run src.eval.egocentric_anchors --seeds 5         # COEXISTING EGOCENTRIC ANCHORS (Nat Commun 2025): egocentric center + object + boundary frames coexist (decode all from the combined population), each specific to its own cells; adds EgocentricCenterCells
run src.eval.local_3d_order   --seeds 5            # LOCAL 3D ORDER not a global lattice (bat MEC): a local-order (blue-noise) field code has high local order but low global lattice -- separable from a true 3D lattice and from random
run src.eval.agent_grid_reanchor --seeds 5         # OBJECT REANCHORING IN THE CORE CORTEX: object-vector cells reanchor the grid phase from INSIDE _HexGridModules.forward(object_obs=) via a shared ego->allo transform; object cue rescues open-field drift where boundaries can't; shuffled-anchor control fails (load-bearing integration)
run src.eval.grid_3d          --seeds 5            # BIOLOGICALLY-GROUNDED 3D GRID CODE (bat MEC; Ginosar 2021): LocalOrder3DGrid wired into _HexGridModules(grid_3d=True) replaces the 1D-z stub -- fields in the bat regime (local order, NO global lattice) vs a cubic-lattice control; path-integrates + localizes in full 3D
run src.eval.content_binding   --seeds 6           # §7 content-binding (what-where-when): conjunctive vs pure time cells + decode what & when (bat CA1 2023)

if [ "${1:-}" = "exploratory" ]; then
  echo; echo "############ EXPLORATORY demos (illustrative; not the central claims) ############"
  for m in emergence boundary_anchoring pillars planning goal_navigation relational continual embodiment generalize_trajectory magnitude_frontier; do
    if python - "$m" <<'PY' 2>/dev/null; then
import importlib.util, sys
sys.exit(0 if importlib.util.find_spec("src.eval." + sys.argv[1]) else 1)
PY
      run "src.eval.$m" || echo "  (skipped src.eval.$m — non-zero exit)"
    fi
  done
fi

echo; echo "############ LANGUAGE results (GPU) ############"
echo "Run on a single T4 (not here): notebooks/m2_extrapolation_multiseed_kaggle.py (multi-seed grid vs place),"
echo "and notebooks/m2_grid_cortex_all_tasks_kaggle.py. See REPRODUCE.md for the figure->command map."
echo "CAPSTONE: notebooks/m5_deadreckoning_llm_kaggle.py -- a frozen LLM reads the emergent HD+grid neural"
echo "  code to answer self-localization (WHERE + egocentric HOME vector); cortex-ON vs text-only-OFF, n=6."
echo; echo "DONE — see results/*.json and results/*.svg"
